## Connection Pool
spring.datasource.hikari.connectionTimeout=20000
spring.datasource.hikari.maximumPoolSize=5

## PostgreSQL (Neon)
spring.datasource.url=jdbc:postgresql://ep-calm-morning-aohwlwef.c-2.ap-southeast-1.aws.neon.tech:5432/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_WHAZgy1ITP7z

## JPA
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update